### ISSUE TITLE
Draft of CLI/API design

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/paneron-cli#1]
This issue is to gather inputs from potential users of this tool.

Assuming the CLI is called `doctl`:

## Initialize a documents register

```console
> doctl init doc-reg-name
> ls
doc-reg-name/
```

## Set register metadata

```console
> cd doc-reg-name/
> doctl set name1 value1
> doctl set-add name1.ary1[] ary_value1
> doctl set-add name1.obj1.ary[] val1
```

## Initialize dataset

A dataset groups together a set of documents.
It is up to the documents register user to decide which documents to be grouped as one.
One document can only belong to one dataset.

```console
> cd doc-reg-name/
> doctl init-dataset my-documents
```

## List datasets

```console
> doctl ls
my-documents
...
```

## Set dataset metadata

```console
> cd doc-reg-name/
> doctl  set datasets.my-documents.meta.name1 value1
> doctl  set-add datasets.my-documents.meta.name1.ary1 ary_value1
> doctl  set-add datasets.my-documents.meta.name1.ary1 ary_value2
> doctl  get datasets.my-documents.meta.name1.ary1
ary_value1
ary_value2
```

## Upload a new document

```console
> doctl upload my-documents/UNIQUE_EXTERNAL_DOCUMENT_ID FILES...
> doctl upload my-documents/UNIQUE_EXTERNAL_DOCUMENT_ID [--status DOC_STATUS] FILES...
```

Under the hood, UNIQUE_EXTERNAL_DOCUMENT_ID will be modelled as an Item Class (ISO 19135).

## Modify document metadata

```console
> doctl set datasets.my-documents.UNIQUE_EXTERNAL_DOCUMENT_ID.status published
> doctl set datasets.my-documents.UNIQUE_EXTERNAL_DOCUMENT_ID.published_date $(date)
```

## List document versions

```console
> doctl ls-versions my-documents/UNIQUE_EXTERNAL_DOCUMENT_ID
...1
...2
...
```

## List document files of a particular version

```console
> doctl ls my-documents/UNIQUE_EXTERNAL_DOCUMENT_ID
...
main.pdf
...
> doctl ls my-documents/UNIQUE_EXTERNAL_DOCUMENT_ID#version_string
...
main.pdf
...

```

## Add a new document version

```console
> doctl upload my-documents/UNIQUE_EXTERNAL_DOCUMENT_ID FILES...
```

## Override a document version

```console
> doctl upload --force my-documents/UNIQUE_EXTERNAL_DOCUMENT_ID#VERSION_STRING FILES...
```

## Remove a document version

```console
> doctl rm my-documents/UNIQUE_EXTERNAL_DOCUMENT_ID#VERSION_STRING
```

## Getting help

```console
> doctl help
> doctl set help
> doctl ls help
> doctl upload help
> doctl rm help
> doctl init help
> doctl init-dataset help
```

**Comment by ronaldtse** [comment]
What's the reason for a purpose specific CLI for documents? So I can't manage other types of content? That can't be right.

**Comment by ronaldtse** [comment]
The new ISO 19135 already provides the underlying model for concept class, concept, register item class and register item. 

These are the concept classes to implement:
- document (across stages but not across years)
- document with stage
- document with stage version

These are the register item classes to implement:
- document
- document with stage
- document with stage version that includes the actual content

I.e you need to create data definitions for these things above. 

We need a generic way of handling these, not hard coding their attributes in code. 

Please refer to how data definitions are expressed and implemented in lutaml-model.

**Comment by ribose-jeffreylau** [comment]
> What's the reason for a purpose specific CLI for documents? So I can't manage other types of content? That can't be right.

Bad name I guess.  It's a temporary name.  Lemme change that.

**Comment by ribose-jeffreylau** [comment]
> What's the reason for a purpose specific CLI for documents? So I can't manage other types of content? That can't be right.

> The new ISO 19135 already provides the underlying model for concept class, concept, register item class and register item.
> 
> These are the concept classes to implement:
> 
>     * document (across stages but not across years)
> 
>     * document with stage
> 
>     * document with stage version
> 
> 
> These are the register item classes to implement:
> 
>     * document
> 
>     * document with stage
> 
>     * document with stage version that includes the actual content
> 
> 
> I.e you need to create data definitions for these things above.
> 
> We need a generic way of handling these, not hard coding their attributes in code.
> 
> Please refer to how data definitions are expressed and implemented in lutaml-model.

Ruby Paneron Register currently only has _concepts_ of register item class and register item, which as I understand, realize "concept classes" and "concepts" from ISO 19135.

If we want to keep the generality of the tools, my thoughts go to something like this:

```console
> ctl --concept-model-map  ./document_with_stages_mapping_to_register_model.lutaml \
    init document_register
> cd document_register
> ctl --concept-model-map  ../document_with_stages_mapping_to_register_model.lutaml \
    init-dataset my-dataset
> ctl --concept-model-map  ../document_with_stages_mapping_to_register_model.lutaml \
    upload  my-dataset/Doc-00001 files...
```

Does this sound like the right direction?

EDIT: I am getting some similar vibe from here: https://github.com/lutaml/lutaml-model/issues/165

**Comment by ribose-jeffreylau** [comment]
## Further ideas & goals

- The tool should be able to fetch external data models (on local disk / hosted on GitHub / _etc._) that are specified on invocation (_impl. details: cached, of course_).
- The data models should provide enough **domain-specific** information for the tool to:
  - perform data **input validation**,
  - **present** generic register items as domain-specific objects,
  - provide **domain-specific interactions** with register items, item classes, metadata, _etc._
    - That implies a need to define a mapping of such domain-specific actions to primitive register actions.
- These data models should ideally be defined in terms of LutaML models.
- The tool should aim to eliminate the need for the user to directly perform any further Git-related tasks (_e.g._, `git tag`) for the purpose of publishing documents, for example.

**Comment by ribose-jeffreylau** [comment]
> * The data models should provide enough **domain-specific** information for the tool to:
>   
>   * perform data **input validation**,
>   * **present** generic register items as domain-specific objects,
>   * provide **domain-specific interactions** with register items, item classes, metadata, _etc._
>     
>     * That implies a need to define a mapping of such domain-specific actions to primitive register actions.
> 
> * These data models should ideally be defined in terms of LutaML models.

These issues may make defining register data models easier:

- [ ] https://github.com/lutaml/lutaml-model/issues/174
- [ ] https://github.com/lutaml/lutaml-model/issues/285

**Comment by ribose-jeffreylau** [comment]
> * The data models should provide enough **domain-specific** information for the tool to:
>   
>   * perform data **input validation**,
>   * **present** generic register items as domain-specific objects,
>   * provide **domain-specific interactions** with register items, item classes, metadata, _etc._
>     
>     * That implies a need to define a mapping of such domain-specific actions to primitive register actions.
> 
> * These data models should ideally be defined in terms of LutaML models.

Brainstorming how a data model definition may look like:

```yaml
---
register:
  concepts:
    - name: Document
      attributes:
        id:
          definition: The unique identifier of the document
          type: string
        year:
          definition: The year the document was published
          type: year
        doctype:
          definition: The Metanorma document type
          type: string
        doc_class:
          definition: The Metanorma document class
          type: string
      relations:
        - target: DocumentStage
          relationship:
            source:
              type: aggregation
              attributes:
                document:
                  cardinality:
                    min: 1
                    max: "*"
            target:
              type: direct
              attributes:
                documentStage:
                  cardinality:
                    min: 1
                    max: "*"
            action:
              verb: comprises
              direction: target
    - name: DocumentStage
      attributes:
        stage:
          definition: The stage of the document
          type: string
      relations:
        - target: DocumentVersion
          relationship:
            source:
              type: aggregation
              attributes:
                documentStage:
                  cardinality:
                    min: 1
                    max: "*"
            target:
              type: direct
              attributes:
                documentVersion:
                  cardinality:
                    min: 1
                    max: "*"
            action:
              verb: comprises
              direction: target
    - name: DocumentVersion
      attributes:
        version:
          definition: The version of the document
          type: string
  data:
    item_classes:
      values: null # No concrete item classes, since we are sorting by Document ID
      # register items with the same Document ID will be grouped together
      # in an item class
      group_by:
        name: Document
        attribute: id
      sort_by:
        attribute: year
        order: desc
    register_items:
      attributes:
        # Here, we map each register item attribute to the corresponding concept
        id:
          definition: The document identifier
          concept: Document
          attribute: id
        stage:
          definition: The stage of the document
          concept: DocumentStage
          attribute: stage
        version:
          definition: The version of the document
          concept: DocumentVersion
          attribute: version
        year:
          definition: The year the document was published
          concept: Document
          attribute: year
        title:
          definition: The title of the document
          type: string
  actions:
    # Here, list out the actions that can be performed on the
    # item classes and register items,
    # and map them to the corresponding functions...
    - name: create_document_version
      use: create_register_item
      parameters:


# ... TBD

```
